/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the source files.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GranolaMergerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultAction: "menu",
  separatorTemplate: "{{notes}}\n\n---\n# Transcript\n\n{{transcript}}",
  filenameSuffix: " (Combined)",
  autoOpenCombined: true
};
var GranolaMergerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("document-merge", "Merge Notes and Transcript", (evt) => {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        const transcriptFile = this.resolveTranscriptFile(activeFile);
        new MergerMenuModal(this.app, this, activeFile, transcriptFile).open();
      } else {
        new import_obsidian.Notice("Please open a meeting note first.");
      }
    });
    this.addCommand({
      id: "open-merger-menu",
      name: "Open Interactive Merger Menu",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            const transcriptFile = this.resolveTranscriptFile(activeFile);
            new MergerMenuModal(this.app, this, activeFile, transcriptFile).open();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "copy-notes-transcript-clipboard",
      name: "Copy Notes and Transcript to Clipboard",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            const transcriptFile = this.resolveTranscriptFile(activeFile);
            if (transcriptFile) {
              this.copyCombinedToClipboard(activeFile, transcriptFile);
            } else {
              new import_obsidian.Notice("No transcript found automatically. Please select it.");
              new TranscriptSelectionModal(this.app, this, activeFile, (selectedFile) => {
                this.copyCombinedToClipboard(activeFile, selectedFile);
              }).open();
            }
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "create-combined-note",
      name: "Create Combined Note",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            const transcriptFile = this.resolveTranscriptFile(activeFile);
            if (transcriptFile) {
              this.createCombinedNote(activeFile, transcriptFile);
            } else {
              new import_obsidian.Notice("No transcript found automatically. Please select it.");
              new TranscriptSelectionModal(this.app, this, activeFile, (selectedFile) => {
                this.createCombinedNote(activeFile, selectedFile);
              }).open();
            }
          }
          return true;
        }
        return false;
      }
    });
    this.addSettingTab(new GranolaMergerSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Resolves the corresponding transcript file for a given active meeting note.
   */
  resolveTranscriptFile(activeFile) {
    const cache = this.app.metadataCache.getFileCache(activeFile);
    if (cache?.frontmatter) {
      for (const key of Object.keys(cache.frontmatter)) {
        if (key.toLowerCase().includes("transcript")) {
          const val = cache.frontmatter[key];
          if (typeof val === "string") {
            const cleanVal = val.replace(/^\[\[/, "").replace(/\]\]$/, "").split("|")[0].trim();
            const file = this.app.metadataCache.getFirstLinkpathDest(cleanVal, activeFile.path);
            if (file)
              return file;
          }
        }
      }
    }
    const allLinks = [...cache?.links || [], ...cache?.embeds || []];
    for (const link of allLinks) {
      const targetPath = link.link;
      const displayText = link.displayText || "";
      if (targetPath.toLowerCase().includes("transcript") || displayText.toLowerCase().includes("transcript")) {
        const file = this.app.metadataCache.getFirstLinkpathDest(targetPath, activeFile.path);
        if (file)
          return file;
      }
    }
    const activeBaseName = activeFile.basename;
    const files = this.app.vault.getMarkdownFiles();
    const candidates = files.filter((f) => {
      if (f.path === activeFile.path)
        return false;
      const name = f.basename.toLowerCase();
      const base = activeBaseName.toLowerCase();
      return name.includes("transcript") && (name.includes(base) || base.includes(name.replace("transcript", "").trim()));
    });
    if (candidates.length > 0) {
      return candidates[0];
    }
    return null;
  }
  /**
   * Helper to merge notes and transcript using separator template.
   */
  mergeContent(notesContent, transcriptContent) {
    return this.settings.separatorTemplate.replace("{{notes}}", notesContent).replace("{{transcript}}", transcriptContent);
  }
  /**
   * Action A: Merge and copy combined content to clipboard.
   */
  async copyCombinedToClipboard(notesFile, transcriptFile) {
    try {
      const notesText = await this.app.vault.cachedRead(notesFile);
      const transcriptText = await this.app.vault.cachedRead(transcriptFile);
      const merged = this.mergeContent(notesText, transcriptText);
      await navigator.clipboard.writeText(merged);
      new import_obsidian.Notice("\u{1F4CB} Notes & Transcript merged and copied to clipboard!");
    } catch (e) {
      new import_obsidian.Notice("\u274C Failed to copy to clipboard: " + e.message);
      console.error(e);
    }
  }
  /**
   * Action B: Merge and create a new unified note file.
   */
  async createCombinedNote(notesFile, transcriptFile) {
    try {
      const notesText = await this.app.vault.cachedRead(notesFile);
      const transcriptText = await this.app.vault.cachedRead(transcriptFile);
      const mergedContent = this.mergeContent(notesText, transcriptText);
      const suffix = this.settings.filenameSuffix || " (Combined)";
      const parentPath = notesFile.parent ? notesFile.parent.path : "";
      let newPath = "";
      if (parentPath === "/" || parentPath === "") {
        newPath = `${notesFile.basename}${suffix}.md`;
      } else {
        newPath = `${parentPath}/${notesFile.basename}${suffix}.md`;
      }
      let targetFile = this.app.vault.getAbstractFileByPath(newPath);
      if (targetFile instanceof import_obsidian.TFile) {
        await this.app.vault.modify(targetFile, mergedContent);
      } else {
        targetFile = await this.app.vault.create(newPath, mergedContent);
      }
      new import_obsidian.Notice(`\u270D\uFE0F Combined note created: ${targetFile.name}`);
      if (this.settings.autoOpenCombined && targetFile instanceof import_obsidian.TFile) {
        const leaf = this.app.workspace.getLeaf(true);
        await leaf.openFile(targetFile);
      }
    } catch (e) {
      new import_obsidian.Notice("\u274C Failed to create combined note: " + e.message);
      console.error(e);
    }
  }
};
var TranscriptSelectionModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, plugin, activeFile, onSelect) {
    super(app);
    this.plugin = plugin;
    this.activeFile = activeFile;
    this.onSelect = onSelect;
    this.setPlaceholder("Search and select a transcript file...");
  }
  getItems() {
    const files = this.app.vault.getMarkdownFiles();
    const activeBase = this.activeFile.basename.toLowerCase();
    return files.filter((f) => f.path !== this.activeFile.path).sort((a, b) => {
      const nameA = a.basename.toLowerCase();
      const nameB = b.basename.toLowerCase();
      let scoreA = 0;
      let scoreB = 0;
      if (nameA.includes("transcript"))
        scoreA += 5;
      if (nameB.includes("transcript"))
        scoreB += 5;
      if (nameA.includes(activeBase) || activeBase.includes(nameA.replace("transcript", "").trim()))
        scoreA += 10;
      if (nameB.includes(activeBase) || activeBase.includes(nameB.replace("transcript", "").trim()))
        scoreB += 10;
      return scoreB - scoreA;
    });
  }
  getItemText(item) {
    return `${item.basename} (${item.path})`;
  }
  onChooseItem(item, evt) {
    this.onSelect(item);
  }
};
var MergerMenuModal = class _MergerMenuModal extends import_obsidian.Modal {
  constructor(app, plugin, activeFile, transcriptFile) {
    super(app);
    this.plugin = plugin;
    this.activeFile = activeFile;
    this.transcriptFile = transcriptFile;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("granola-merger-modal");
    const headerEl = contentEl.createDiv({ cls: "granola-merger-header" });
    headerEl.createEl("h2", { text: "Merge Notes and Transcript", cls: "granola-merger-title" });
    headerEl.createDiv({ text: "Quickly combine meeting notes and transcripts for easy pasting or archiving.", cls: "granola-merger-subtitle" });
    const statusContainer = contentEl.createDiv({ cls: "granola-merger-status-container" });
    const notesCard = statusContainer.createDiv({ cls: "granola-merger-card" });
    notesCard.createDiv({ text: "Active Note File", cls: "granola-merger-card-title" });
    notesCard.createDiv({ text: this.activeFile.basename + ".md", cls: "granola-merger-card-value" });
    const transcriptCard = statusContainer.createDiv({ cls: "granola-merger-card" });
    transcriptCard.createDiv({ text: "Linked Transcript File", cls: "granola-merger-card-title" });
    const transcriptValEl = transcriptCard.createDiv({ cls: "granola-merger-card-value" });
    if (this.transcriptFile) {
      transcriptValEl.setText(this.transcriptFile.basename + ".md");
    } else {
      transcriptValEl.createSpan({ text: "No transcript file detected automatically.", cls: "granola-merger-card-error" });
    }
    const actionGrid = contentEl.createDiv({ cls: "granola-merger-action-grid" });
    const copyBtn = actionGrid.createEl("button", {
      cls: "granola-merger-btn granola-merger-btn-primary",
      text: "\u{1F4CB} Copy to Clipboard"
    });
    if (!this.transcriptFile) {
      copyBtn.setAttribute("disabled", "true");
      copyBtn.style.opacity = "0.5";
      copyBtn.style.cursor = "not-allowed";
    } else {
      copyBtn.addEventListener("click", async () => {
        if (this.transcriptFile) {
          await this.plugin.copyCombinedToClipboard(this.activeFile, this.transcriptFile);
          this.close();
        }
      });
    }
    const saveBtn = actionGrid.createEl("button", {
      cls: "granola-merger-btn granola-merger-btn-primary",
      text: "\u270D\uFE0F Create Combined Note"
    });
    if (!this.transcriptFile) {
      saveBtn.setAttribute("disabled", "true");
      saveBtn.style.opacity = "0.5";
      saveBtn.style.cursor = "not-allowed";
    } else {
      saveBtn.addEventListener("click", async () => {
        if (this.transcriptFile) {
          await this.plugin.createCombinedNote(this.activeFile, this.transcriptFile);
          this.close();
        }
      });
    }
    const changeBtn = actionGrid.createEl("button", {
      cls: "granola-merger-btn granola-merger-btn-secondary granola-merger-btn-full",
      text: "\u{1F50D} Select / Change Transcript File"
    });
    changeBtn.addEventListener("click", () => {
      this.close();
      new TranscriptSelectionModal(this.app, this.plugin, this.activeFile, (selectedFile) => {
        new _MergerMenuModal(this.app, this.plugin, this.activeFile, selectedFile).open();
      }).open();
    });
    const previewHeader = contentEl.createDiv({ cls: "granola-merger-preview-header" });
    previewHeader.createSpan({ text: "Live Preview of Combined Markdown" });
    const previewBox = contentEl.createDiv({ cls: "granola-merger-preview-box", text: "Loading preview..." });
    this.loadPreview(previewBox);
  }
  async loadPreview(previewBox) {
    try {
      const notesText = await this.app.vault.cachedRead(this.activeFile);
      let transcriptText = "";
      if (this.transcriptFile) {
        transcriptText = await this.app.vault.cachedRead(this.transcriptFile);
      } else {
        transcriptText = "_[No transcript content. Please select a transcript file.]_";
      }
      const merged = this.plugin.mergeContent(notesText, transcriptText);
      previewBox.setText(merged);
    } catch (e) {
      previewBox.setText("Error loading preview: " + e.message);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var GranolaMergerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Granola Notes and Transcript Merger Settings" });
    new import_obsidian.Setting(containerEl).setName("Default Action").setDesc("Choose what happens when you run the merger command directly on an active note.").addDropdown(
      (dropdown) => dropdown.addOption("menu", "Show Interactive Merger Menu").addOption("copy", "Directly Copy Combined to Clipboard").addOption("save", "Directly Create Combined Note").setValue(this.plugin.settings.defaultAction).onChange(async (value) => {
        this.plugin.settings.defaultAction = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Combined Note Filename Suffix").setDesc("The suffix added to the note name when creating a combined note file.").addText(
      (text) => text.setPlaceholder(" (Combined)").setValue(this.plugin.settings.filenameSuffix).onChange(async (value) => {
        this.plugin.settings.filenameSuffix = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-Open Combined Note").setDesc("Automatically open the newly created combined note file in a new tab.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoOpenCombined).onChange(async (value) => {
        this.plugin.settings.autoOpenCombined = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Separator & Combination Template").setDesc("Customize the format of the merged document. Use {{notes}} and {{transcript}} as placeholders.").addTextArea(
      (text) => text.setPlaceholder("{{notes}}\n\n---\n# Transcript\n\n{{transcript}}").setValue(this.plugin.settings.separatorTemplate).onChange(async (value) => {
        this.plugin.settings.separatorTemplate = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
